---
# tasks file for vector
- name: Get_vector_version
  ansible.builtin.command: vector --version
  register: is_installed
  ignore_errors: True
- name: Create a directory Vector
  ansible.builtin.file: 
    path: ./vector 
    state: directory
    owner: netology
    group: netology
    mode: 0755
  when:
    - is_installed is failed
- name: Copy rpm file to server
  ansible.builtin.get_url:
    url: "{{vector_url}}"
    dest: ./vector/vector-{{vector_version}}-1.x86_64.rpm
    mode: 0700
  when:
    - is_installed is failed
- name: Install package
  ansible.builtin.yum:
    disable_gpg_check: true
    name: ./vector/vector-{{vector_version}}-1.x86_64.rpm
    state: present
  when:
    - is_installed is failed
- name: Create vector config
  ansible.builtin.template:
    src: templates/vector.yml.j2
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
- name: Create vector systemd unit
  ansible.builtin.template:
    src: templates/vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: true
  notify: Start Vector service