apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology
  labels:
    app: netology
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netology
  template:
    metadata:
      labels:
        app: netology
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.1
        ports:
        - containerPort: 80
      - name: network-multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
          - name: HTTPS_PORT
            value: "8443"
        ports:
          - containerPort: 8080
          - containerPort: 8443