apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: init-service
          image: busybox:1.36.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          command: [ 'sh', '-c', "until nslookup nginx-svc.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done" ]
      containers:
      - name: nginx
        image: nginx:1.27.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
