---
vector_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
vector_version: 0.32.0
vector_config_dir: "/etc/vector"
vector_config:
  sources:
    demo_logs:
      type: demo_logs
      format: json
      interval: 0.1
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - demo_logs
      database: logs
      endpoint: 84.201.188.70
      table: vector_table
      compression: gzip
      healthcheck: true
      skip_unknown_fields: true