---
- name: Module role
  hosts: localhost
  collections:
    - my_own_namespace.yandex_cloud_elk
  tasks:
    - name: Import createfile role
      ansible.builtin.import_role:
        name: create_file
