--- 
  - src: git@github.com:gemeral68/clickhouse-role.git
    scm: git
    name: clickhouse-role

  - src: git@github.com:gemeral68/lighthouse-role.git
    scm: git
    name: lighthouse-role

  - src: git@github.com:gemeral68/vector-role.git
    scm: git
    name: vector-role
