{
 "title": "Netology",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPUla",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15" },
    { "expr": "node_load5" },
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Free RAM mem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "Free HDD mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/vda2\", fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}\r"
    }
   ]
  }
 ]
}